"""Cria tabelas users e lesson_plans

Revision ID: 16db07e5cf85
Revises: 8f8dd29112e4
Create Date: 2025-06-19 19:07:08.690627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16db07e5cf85'
down_revision: Union[str, Sequence[str], None] = '8f8dd29112e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
