"""Cria tabelas users e lesson_plans

Revision ID: 8f8dd29112e4
Revises: d5e4c637e88e
Create Date: 2025-06-19 19:00:35.759514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f8dd29112e4'
down_revision: Union[str, Sequence[str], None] = 'd5e4c637e88e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lesson_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic', sa.String(), nullable=True),
    sa.Column('grade', sa.String(), nullable=True),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lesson_plans_id'), 'lesson_plans', ['id'], unique=False)
    op.create_index(op.f('ix_lesson_plans_topic'), 'lesson_plans', ['topic'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lesson_plans_topic'), table_name='lesson_plans')
    op.drop_index(op.f('ix_lesson_plans_id'), table_name='lesson_plans')
    op.drop_table('lesson_plans')
    # ### end Alembic commands ###
