"""Cria tabelas users e lesson_plans

Revision ID: d5e4c637e88e
Revises: 6f06ccce6aef
Create Date: 2025-06-19 18:57:17.540765

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5e4c637e88e'
down_revision: Union[str, Sequence[str], None] = '6f06ccce6aef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
