"""Adiciona campo name na tabela users

Revision ID: ff92aa7678d1
Revises: 4206d6dae2a8
Create Date: 2025-06-20 23:44:33.487247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff92aa7678d1'
down_revision: Union[str, Sequence[str], None] = '4206d6dae2a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
